import os
import re
import requests

OLLAMA_URL = os.getenv(
    "OLLAMA_URL",
    "http://127.0.0.1:11434/api/generate"
)

OLLAMA_MODEL = os.getenv(
    "OLLAMA_MODEL",
    "gemma3:1b"
)


def clean_ai_analysis(text: str) -> str:
    """
    Keep only the required 4 sections from the AI response.
    Removes extra sections generated by the model.
    """

    if not text:
        return ""

    text = text.strip()

    # Find the beginning of the required sections.
    section_pattern = re.compile(
        r"(?im)^\s*(?:\*{0,2}\s*)?"
        r"(1\.\s*Threat Summary|"
        r"2\.\s*Why It Is Risky|"
        r"3\.\s*Investigation Steps|"
        r"4\.\s*Recommended Action)"
        r"(?:\s*\*{0,2})?\s*:?\s*"
    )

    matches = list(section_pattern.finditer(text))

    if not matches:
        return text[:1200].strip()

    # Keep only the first four recognized sections.
    sections = {}

    for index, match in enumerate(matches):
        title = match.group(1).strip()

        if title.startswith("1."):
            key = "1. Threat Summary"
        elif title.startswith("2."):
            key = "2. Why It Is Risky"
        elif title.startswith("3."):
            key = "3. Investigation Steps"
        elif title.startswith("4."):
            key = "4. Recommended Action"
        else:
            continue

        start = match.end()

        if index + 1 < len(matches):
            end = matches[index + 1].start()
        else:
            end = len(text)

        content = text[start:end].strip()

        # Remove accidental markdown heading symbols.
        content = re.sub(r"^\s*[:\-]+\s*", "", content).strip()

        sections[key] = content

    # Build the final response in the required order.
    final_parts = []

    # Section 1
    if "1. Threat Summary" in sections:
        content = sections["1. Threat Summary"]

        # Keep only the first sentence for concise output.
        sentences = re.split(r"(?<=[.!?])\s+", content)
        content = sentences[0].strip()

        final_parts.append(
            f"1. Threat Summary\n{content}"
        )

    # Section 2
    if "2. Why It Is Risky" in sections:
        content = sections["2. Why It Is Risky"]

        sentences = re.split(r"(?<=[.!?])\s+", content)
        content = sentences[0].strip()

        final_parts.append(
            f"2. Why It Is Risky\n{content}"
        )

    # Section 3
    if "3. Investigation Steps" in sections:
        content = sections["3. Investigation Steps"]

        # Extract bullet points.
        bullets = re.findall(
            r"(?m)^\s*(?:[•*\-]|\d+[.)])\s*(.+)$",
            content
        )

        # If model did not use bullets, split lines.
        if not bullets:
            lines = [
                line.strip()
                for line in content.splitlines()
                if line.strip()
            ]
            bullets = lines

        bullets = bullets[:2]

        final_parts.append(
            "3. Investigation Steps\n" +
            "\n".join(f"• {bullet}" for bullet in bullets)
        )

    # Section 4
    if "4. Recommended Action" in sections:
        content = sections["4. Recommended Action"]

        bullets = re.findall(
            r"(?m)^\s*(?:[•*\-]|\d+[.)])\s*(.+)$",
            content
        )

        if not bullets:
            lines = [
                line.strip()
                for line in content.splitlines()
                if line.strip()
            ]
            bullets = lines

        bullets = bullets[:2]

        final_parts.append(
            "4. Recommended Action\n" +
            "\n".join(f"• {bullet}" for bullet in bullets)
        )

    return "\n\n".join(final_parts).strip()


def analyze_security_incident(
    threat_type,
    severity,
    risk_score,
    source_ip,
    username,
    description
):
    prompt = f"""
You are SentinelX AI Security Copilot.

Analyze this cybersecurity incident:

Threat: {threat_type}
Severity: {severity}
Risk Score: {risk_score}/100
Source IP: {source_ip}
Username: {username}
Description: {description}

Return ONLY these four sections:

1. Threat Summary
One short sentence.

2. Why It Is Risky
One short sentence.

3. Investigation Steps
Exactly 2 bullet points.

4. Recommended Action
Exactly 2 bullet points.

STRICT RULES:
- Do not create sections 5 or higher.
- Do not create Additional Notes.
- Do not create Further Analysis.
- Do not create Conclusion.
- Do not repeat information.
- Do not invent facts.
- Do not claim an action was already performed.
- Do not include greetings.
- Do not include introductory text.
- Stop immediately after section 4.
- Keep the response concise.
"""

    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model": OLLAMA_MODEL,
                "prompt": prompt,
                "stream": False,
                "options": {
                    "temperature": 0.1,
                    "num_predict": 250
                }
            },
            timeout=30,
        )

        response.raise_for_status()

        data = response.json()
        raw_analysis = data.get("response", "").strip()

        if not raw_analysis:
            return {
                "success": False,
                "model": OLLAMA_MODEL,
                "analysis": "AI Security Copilot returned an empty response.",
            }

        # Clean model output before sending it to the frontend.
        analysis = clean_ai_analysis(raw_analysis)

        if not analysis:
            return {
                "success": False,
                "model": OLLAMA_MODEL,
                "analysis": "AI Security Copilot could not format the analysis.",
            }

        return {
            "success": True,
            "model": OLLAMA_MODEL,
            "analysis": analysis,
        }

    except requests.exceptions.Timeout:
        return {
            "success": False,
            "model": OLLAMA_MODEL,
            "analysis": "AI Security Copilot timed out. Please try again.",
            "error": "Ollama request timed out.",
        }

    except requests.exceptions.ConnectionError:
        return {
            "success": False,
            "model": OLLAMA_MODEL,
            "analysis": "Unable to connect to Ollama. Make sure Ollama is running.",
            "error": "Ollama connection failed.",
        }

    except requests.exceptions.HTTPError as error:
        return {
            "success": False,
            "model": OLLAMA_MODEL,
            "analysis": "Ollama returned an HTTP error.",
            "error": str(error),
        }

    except Exception as error:
        return {
            "success": False,
            "model": OLLAMA_MODEL,
            "analysis": "AI Security Copilot is currently unavailable.",
            "error": str(error),
        }